deploy: True
project_name: "peg-probing"
seed: 42

lang: "dyck-1"
work_dir: "../Aux"
device : "cpu"

data:
  max_len: 30
  num_iters: 8192
  batch_size: 32
  precomp: True
  save_dir: "data"
  num_workers: 0

shenanigans:
  max_len: 30
  num_iters: 10
  batch_size: 1
  precomp: False
  save_dir: "data"
  num_workers: 0

eval:
  max_len: 30
  num_iters: 5
  batch_size: 1
  precomp: False
  save_dir: "data"
  num_workers: 0

model:
  n_l: 2
  d_m: 96
  d_h: 32
  n_ctx: 32
  act_fn: "gelu"
  act_cache: True
  checkpoint: 5000

train:
  bf16: False
  epochs: 15

probe:
  d_m: 96
  linear: True
  checkpoint: 1800

parse:
  max_len: 30
  num_iters: 128
  batch_size: 1
  precomp: False
  save_dir: "data"
  num_workers: 0

optim:
  learning_rate: 2e-2
  min_lr: 2e-3
  weight_decay: 1e-5
  momentum: 0.9
  grad_clip: 1.0
  decay_lr: False
  warmup_steps: 0
  restart_steps: 2000
  decay_factor: 5e-4
  scheduler: "cosine"

log: 
  save_multiple: True
  train_interval: 1
  eval_interval: 0
  save_interval: 200
  free: False


defaults:
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

hydra:
  output_subdir: Null
  job:
    chdir: False
  run:
    dir: .

  sweep:
    dir: .
    subdir: .
