deploy: True
project_name: "peg-probing"
seed: 42

lang: "dyck-2"
work_dir: "../Aux"
device : "cpu"
model_type: "recognizer"
probe_type: "parse_state"

data:
  max_len: 30
  num_iters: 64000
  batch_size: 32
  precomp: True
  save_dir: "data"
  num_workers: 0
  pos_ratio: 0.5

eval:
  max_len: 30
  num_iters: 50
  batch_size: 1
  precomp: False
  save_dir: "data"
  num_workers: 0
  pos_ratio: 0.6
  temperature: 0.5

parse:
  max_len: 30
  num_iters: 2000
  batch_size: 1
  precomp: False
  save_dir: "data"
  num_workers: 0
  pos_ratio: 1.0
  temperature: 0.5

model:
  n_l: 2
  d_m: 128
  n_h: 4
  n_ctx: 32
  dropout: 0.0
  bias: False
  attn_dir: "causal"
  act_fn: "gelu"
  act_cache: True
  checkpoint: 10000

train:
  bf16: True
  epochs: 5

probe:
  d_mlp: 512
  linear: True
  checkpoint: 1800

optim:
  optimizer: "adamw"
  weight_decay: 1e-5
  momentum: 0.9
  beta1: 0.9
  beta2: 0.95
  eps: 1e-6
  grad_clip: 1.0
  decay_lr: True
  scheduler: "cosine"
  warmup_steps: 0
  restart_steps: 5000
  decay_factor: 5e-4
  learning_rate: 1e-3
  min_lr: 1e-4

log: 
  save_multiple: True
  train_interval: 50
  eval_interval: 50
  save_interval: 1000
  debug: False
  free: False


defaults:
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

hydra:
  output_subdir: Null
  job:
    chdir: False
  run:
    dir: .

  sweep:
    dir: .
    subdir: .
