deploy: True
project_name: "peg-probing"
seed: 42

work_dir: "/scratch/druhan.probing"

data:
  language: "triple"
  max_len: 62
  num_iters: 1000000
  batch_size: 128 
  num_workers: 0
  precomp: True
  save_dir: 'data'

model:
  n_layers: 2
  n_embd: 128
  n_ctx: 64
  d_model: 128
  d_head: 64

train:
  bf16: True
  epochs: 15
  device : "cuda"

optim:
  learning_rate: 1e-3
  weight_decay: 1e-4
  beta1: 0.9
  beta2: 0.95
  grad_clip: 1.0
  decay_lr: True
  warmup_steps: 200
  min_lr: 9e-4

eval:
  save_tables: True
  grammar: True
  num_samples: 2500

log: 
  save_multiple: False
  train_interval: 1000
  eval_interval: 1000
  save_interval: 1000
  free: False


# Nested configs. Disable hydra logging
defaults:
  - _self_
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

# Disable hydra directory structure
hydra:
  output_subdir: Null
  job:
    chdir: False
  run:
    dir: .

  sweep:
    dir: .
    subdir: .
