deploy: False
project_name: "peg-probing"
seed: 42

work_dir: "/scratch/druhan.probing"
device : "cuda"

data:
  language: "star"
  max_len: 62
  num_iters: 100000
  batch_size: 128 
  num_workers: 0
  precomp: True
  save_dir: "data"

eval:
  language: "expr"
  max_len: 62
  num_iters: 1000
  batch_size: 1
  num_workers: 0
  precomp: False
  save_dir: "data"

model:
  n_layers: 2
  d_model: 256
  d_head: 64
  n_ctx: 64
  act_fn: 'gelu'
  attention_dir: "bidirectional"
  n_devices: 1

train:
  bf16: True
  epochs: 15

optim:
  learning_rate: 1e-3
  weight_decay: 1e-4
  beta1: 0.9
  beta2: 0.95
  grad_clip: 1.0
  decay_lr: True
  warmup_steps: 200
  min_lr: 9e-4

log: 
  save_multiple: False
  train_interval: 1000
  eval_interval: 1000
  save_interval: 1000
  free: False


defaults:
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

hydra:
  output_subdir: Null
  job:
    chdir: False
  run:
    dir: .

  sweep:
    dir: .
    subdir: .
