# @package _global_
deploy: False
project_name: "peg-probing"
seed: 42
lang: "dyck-2"
work_dir: "../Aux"
device: "cpu"

experiment:
  task: "train_model"

model:
  type: "recognizer"
  n_l: 2
  d_m: 128
  n_h: 4
  n_ctx: 32
  dropout: 0.0
  bias: False
  attn_dir: "causal"
  act_fn: "gelu"
  act_cache: True
  checkpoint: 10000

data:
  max_len: 30
  num_iters: 64000
  batch_size: 32
  precomp: True
  num_workers: 0
  pos_ratio: 0.5

shenanigans:
  max_len: 30
  num_iters: 5
  batch_size: 1
  precomp: False
  num_workers: 0
  pos_ratio: 0.5

probe:
  type: "parse_state"
  d_mlp: 512
  linear: True
  checkpoint: 1800

eval:
  batch_size: 1
  num_samples: 50
  temperature: 0.5

optim:
  optimizer: "adamw"
  learning_rate: 1e-3
  weight_decay: 1e-5
  momentum: 0.9
  beta1: 0.9
  beta2: 0.95
  eps: 1e-6
  grad_clip: 1.0
  decay_lr: True
  scheduler: "cosine"
  warmup_steps: 0
  restart_steps: 5000
  min_lr: 1e-4

log:
  train_interval: 50
  eval_interval: 50
  save_interval: 1000
  debug: False

hydra:
  run:
    dir: .
