deploy: False
project_name: "peg-probing"
seed: 42

lang: "dyck-1"
work_dir: "../Aux"
device : "cpu"
model_type: "generator"

data:
  max_len: 30
  num_samples: 8192
  batch_size: 32
  precomp: True
  save_dir: "data"
  num_workers: 0

shenanigans:
  max_len: 30
  num_samples: 10
  batch_size: 1
  precomp: False
  save_dir: "data"
  num_workers: 0

eval:
  max_len: 30
  num_samples: 128
  batch_size: 1
  precomp: False
  save_dir: "data"
  num_workers: 0

model:
  n_l: 2
  d_m: 128
  d_h: 32
  n_ctx: 32
  attn_dir: "causal"
  act_fn: "gelu"
  act_cache: False
  checkpoint: 5000

train:
  bf16: True
  epochs: 10

probe:
  d_m: 96
  linear: True
  checkpoint: 1800

optim:
  learning_rate: 3e-2
  min_lr: 1e-3
  weight_decay: 1e-5
  momentum: 0.9
  grad_clip: 1.0
  decay_lr: True
  warmup_steps: 0
  restart_steps: 2000
  decay_factor: 5e-4
  scheduler: "cosine"

log: 
  save_multiple: True
  train_interval: 50
  eval_interval: 50
  save_interval: 500
  free: False


defaults:
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

hydra:
  output_subdir: Null
  job:
    chdir: False
  run:
    dir: .

  sweep:
    dir: .
    subdir: .
